stages:
  - docker
  - deploy

variables:
  CONTAINER_IMAGE: registry.gitlab.com/vp_projects/e2e-titanic
  KUBECONFIG:  /root/.kube/config


docker_image_build_release:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: docker
  only:
    - master
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/src/Dockerfile --destination $CI_REGISTRY_IMAGE:latest

deploy:
  image: dtzar/helm-kubectl
  stage: deploy
  only:
      - master
  before_script:
      - sed -ie "s/deploy-date-value/$(date)/g" kubernetes/deployment.yaml
      - mkdir -p /root/.kube/ && touch /root/.kube/config
      - echo ${KUBERNETES_KUBE_CONFIG} | base64 -d > ${KUBECONFIG}
  script:
      - kubectl apply -f kubernetes/deployment.yaml