version: '3.7'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    #command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 80
    volumes:
      - ./app:/app
    ports:
      - 8002:80
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
